/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PwcSimpleCard {
    'cardDetails': string;
    'cardTitle': string;
    'source': any;
  }
}

declare global {


  interface HTMLPwcSimpleCardElement extends Components.PwcSimpleCard, HTMLStencilElement {}
  var HTMLPwcSimpleCardElement: {
    prototype: HTMLPwcSimpleCardElement;
    new (): HTMLPwcSimpleCardElement;
  };
  interface HTMLElementTagNameMap {
    'pwc-simple-card': HTMLPwcSimpleCardElement;
  }
}

declare namespace LocalJSX {
  interface PwcSimpleCard {
    'cardDetails'?: string;
    'cardTitle'?: string;
    'source'?: any;
  }

  interface IntrinsicElements {
    'pwc-simple-card': PwcSimpleCard;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pwc-simple-card': LocalJSX.PwcSimpleCard & JSXBase.HTMLAttributes<HTMLPwcSimpleCardElement>;
    }
  }
}


